services:
  app:
    # Sử dụng image đẩy lên GHCR
    image: ghcr.io/locmaymo/tim:latest
    container_name: app
    restart: unless-stopped

    # Lấy biến môi trường từ file .env (nằm ở cùng cấp với docker-compose.yaml)
    env_file: .env

    # Nếu muốn override, có thể dùng environment để chỉ định giá trị mặc định khi .env thiếu
    environment:
      APP_ENV: ${APP_ENV:-production}
      DB_CONNECTION: ${DB_CONNECTION:-mysql}
      DB_HOST: ${DB_HOST:-mysql}
      DB_PORT: ${DB_PORT:-3306}
      DB_DATABASE: ${DB_DATABASE:-tim}
      DB_USERNAME: ${DB_USERNAME:-root}
      DB_PASSWORD: ${DB_PASSWORD:-root}

    # Mount các thư mục cần thiết (để lưu trữ, cache)
    volumes:
      - ./storage:/var/www/html/storage
      - ./bootstrap/cache:/var/www/html/bootstrap/cache

    depends_on:
      - mysql
    networks:
      - tim

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-root}
      MYSQL_DATABASE: ${DB_DATABASE:-tim}
      MYSQL_USER: ${DB_USERNAME:-root}
      MYSQL_PASSWORD: ${DB_PASSWORD:-root}
    volumes:
      - dbdata:/var/lib/mysql
      - ./laravel.sql:/docker-entrypoint-initdb.d/laravel.sql
      - ./my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - "3306:3306"
    networks:
      - tim

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
    # Mount mã nguồn và file cấu hình Nginx
    volumes:
      - .:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - tim

  redis:
    image: redis:alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - tim

volumes:
  dbdata:

networks:
  tim:
